In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

%matplotlib inline

#this file path can be changed depending on where you want to work.
#for me, this folder is the root folder for all my ml_learning projects
ROOT_DIR = os.path.join('C:\\', 'users', 'sebas', 'onedrive', 'python', 'machine_learning', 'ml_learning')

#this data path is specific for the iowa housing project, and its where the datasets are stored on my local machine
DATA_PATH = os.path.join(ROOT_DIR, 'datasets', 'iowa_housing')

def load_data(filename, data_path=DATA_PATH):
    '''This function will load the data as a pandas dataframe. it takes the filename 
    as an argument which should be the name that the csv file is saved as in your directory.'''
    
    csv_path = os.path.join(data_path, filename)
    return pd.read_csv(csv_path).fillna(0) #we import the data with the null values replaced with 0s right off the bat. this avoids us having to do it later

training_data = load_data('train.csv')

training_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,0,Reg,Lvl,AllPub,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,0,Reg,Lvl,AllPub,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,0,IR1,Lvl,AllPub,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,0,IR1,Lvl,AllPub,...,0,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,0,IR1,Lvl,AllPub,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [3]:
#here we are setting the Id column as the index instead of having a seperate column for index
#the inplace=True parameter makes the changes to occur on the actual dataframe instead of creating a copy.
training_data.set_index('Id', inplace=True)
training_data.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,0,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,0,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,0,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,0,IR1,Lvl,AllPub,Corner,...,0,0,0,0,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,0,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [4]:
#lets use the describe method to get a better understanding of what this data looks like
training_data.describe()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,56.897260,57.623288,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.117123,443.639726,46.549315,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,42.300571,34.664304,9981.264932,1.382997,1.112799,30.202904,20.645407,180.731373,456.098091,161.319273,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,20.000000,0.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,20.000000,42.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,50.000000,63.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,0.000000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,70.000000,79.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,164.250000,712.250000,0.000000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1474.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [5]:
#notice all the columns which contains missing values in this dataset.
#there are lots of columns here to deal with, make sure to look through it carefully and see what is relevant
#and what is not relevant

training_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1 to 1460
Data columns (total 80 columns):
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1460 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            1460 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1460 non-null object
MasVnrArea       1460 non-null float64
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1460 non-null object
BsmtCond         1460 non-null object
BsmtExposure     1460 non-null object
BsmtFinType1     1460 non-null object
BsmtFinSF1       1460 non-null int64
BsmtFinType2     1460 non-null object
BsmtFinSF2       1460 non-null int64
BsmtUnfSF        1460 non-null int64
TotalBsmtSF      1460 non-null int64
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1460 non-null object
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
LowQualFinSF     1460 non-null int64
GrLivArea        1460 non-null int64
BsmtFullBath     1460 non-null int64
BsmtHalfBath     1460 non-null int64
FullBath         1460 non-null int64
HalfBath         1460 non-null int64
BedroomAbvGr     1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null object
TotRmsAbvGrd     1460 non-null int64
Functional       1460 non-null object
Fireplaces       1460 non-null int64
FireplaceQu      1460 non-null object
GarageType       1460 non-null object
GarageYrBlt      1460 non-null float64
GarageFinish     1460 non-null object
GarageCars       1460 non-null int64
GarageArea       1460 non-null int64
GarageQual       1460 non-null object
GarageCond       1460 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
PoolQC           1460 non-null object
Fence            1460 non-null object
MiscFeature      1460 non-null object
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
SalePrice        1460 non-null int64
dtypes: float64(3), int64(34), object(43)
memory usage: 923.9+ KB

In [6]:
#lets make a copy of the dataset that contains only the columns which have categorical values, not numerical values
train_df_cats = training_data.select_dtypes(include=['object']).copy()

#now lets see the how many null valuesare in each column

print(train_df_cats.isnull().sum())

MSZoning         0
Street           0
Alley            0
LotShape         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrType       0
ExterQual        0
ExterCond        0
Foundation       0
BsmtQual         0
BsmtCond         0
BsmtExposure     0
BsmtFinType1     0
BsmtFinType2     0
Heating          0
HeatingQC        0
CentralAir       0
Electrical       0
KitchenQual      0
Functional       0
FireplaceQu      0
GarageType       0
GarageFinish     0
GarageQual       0
GarageCond       0
PavedDrive       0
PoolQC           0
Fence            0
MiscFeature      0
SaleType         0
SaleCondition    0
dtype: int64

In [7]:
training_data = training_data.apply(lambda x: x.astype('|S') if x.dtype == 'object' else x, axis=0)

In [8]:
training_data

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,b'RL',65.0,8450,b'Pave',b'0',b'Reg',b'Lvl',b'AllPub',b'Inside',...,0,b'0',b'0',b'0',0,2,2008,b'WD',b'Normal',208500
2,20,b'RL',80.0,9600,b'Pave',b'0',b'Reg',b'Lvl',b'AllPub',b'FR2',...,0,b'0',b'0',b'0',0,5,2007,b'WD',b'Normal',181500
3,60,b'RL',68.0,11250,b'Pave',b'0',b'IR1',b'Lvl',b'AllPub',b'Inside',...,0,b'0',b'0',b'0',0,9,2008,b'WD',b'Normal',223500
4,70,b'RL',60.0,9550,b'Pave',b'0',b'IR1',b'Lvl',b'AllPub',b'Corner',...,0,b'0',b'0',b'0',0,2,2006,b'WD',b'Abnorml',140000
5,60,b'RL',84.0,14260,b'Pave',b'0',b'IR1',b'Lvl',b'AllPub',b'FR2',...,0,b'0',b'0',b'0',0,12,2008,b'WD',b'Normal',250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,b'RL',62.0,7917,b'Pave',b'0',b'Reg',b'Lvl',b'AllPub',b'Inside',...,0,b'0',b'0',b'0',0,8,2007,b'WD',b'Normal',175000
1457,20,b'RL',85.0,13175,b'Pave',b'0',b'Reg',b'Lvl',b'AllPub',b'Inside',...,0,b'0',b'MnPrv',b'0',0,2,2010,b'WD',b'Normal',210000
1458,70,b'RL',66.0,9042,b'Pave',b'0',b'Reg',b'Lvl',b'AllPub',b'Inside',...,0,b'0',b'GdPrv',b'Shed',2500,5,2010,b'WD',b'Normal',266500
1459,20,b'RL',68.0,9717,b'Pave',b'0',b'Reg',b'Lvl',b'AllPub',b'Inside',...,0,b'0',b'0',b'0',0,4,2010,b'WD',b'Normal',142125
1460,20,b'RL',75.0,9937,b'Pave',b'0',b'Reg',b'Lvl',b'AllPub',b'Inside',...,0,b'0',b'0',b'0',0,6,2008,b'WD',b'Normal',147500

After looking at all the categories with missing values and comparing them to the data_description.txt file provided, we can see that all the categories with missing
values are because they dont have any, and its not that its missing, so we can fill all the NAN values with 0, and then do something like label encoding for all the other categories to turn any other input into a number

In [9]:
#lets split this dataset into a seperate testing and training set so that we can evaluate our model, even though there is already a testing set provided.
from sklearn.model_selection import train_test_split
train_set, test_set, y_train, y_test = train_test_split(training_data, training_data.SalePrice, test_size=0.2, random_state=42)

train_set_cats = train_set.select_dtypes(include=['object'].copy()) #this line will show you all the columns which have a categorical value, if you needed to know that

In [10]:
train_set

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
255,20,b'RL',70.0,8400,b'Pave',b'0',b'Reg',b'Lvl',b'AllPub',b'Inside',...,0,b'0',b'0',b'0',0,6,2010,b'WD',b'Normal',145000
1067,60,b'RL',59.0,7837,b'Pave',b'0',b'IR1',b'Lvl',b'AllPub',b'Inside',...,0,b'0',b'0',b'0',0,5,2009,b'WD',b'Normal',178000
639,30,b'RL',67.0,8777,b'Pave',b'0',b'Reg',b'Lvl',b'AllPub',b'Inside',...,0,b'0',b'MnPrv',b'0',0,5,2008,b'WD',b'Normal',85000
800,50,b'RL',60.0,7200,b'Pave',b'0',b'Reg',b'Lvl',b'AllPub',b'Corner',...,0,b'0',b'MnPrv',b'0',0,6,2007,b'WD',b'Normal',175000
381,50,b'RL',50.0,5000,b'Pave',b'Pave',b'Reg',b'Lvl',b'AllPub',b'Inside',...,0,b'0',b'0',b'0',0,5,2010,b'WD',b'Normal',127000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1096,20,b'RL',78.0,9317,b'Pave',b'0',b'IR1',b'Lvl',b'AllPub',b'Inside',...,0,b'0',b'0',b'0',0,3,2007,b'WD',b'Normal',176432
1131,50,b'RL',65.0,7804,b'Pave',b'0',b'Reg',b'Lvl',b'AllPub',b'Inside',...,0,b'0',b'MnPrv',b'0',0,12,2009,b'WD',b'Normal',135000
1295,20,b'RL',60.0,8172,b'Pave',b'0',b'Reg',b'Lvl',b'AllPub',b'Inside',...,0,b'0',b'0',b'0',0,4,2006,b'WD',b'Normal',115000
861,50,b'RL',55.0,7642,b'Pave',b'0',b'Reg',b'Lvl',b'AllPub',b'Corner',...,0,b'0',b'GdPrv',b'0',0,6,2007,b'WD',b'Normal',189950
1127,120,b'RL',53.0,3684,b'Pave',b'0',b'Reg',b'Lvl',b'AllPub',b'Inside',...,0,b'0',b'0',b'0',0,6,2009,b'WD',b'Normal',174000

In [11]:
X_train = train_set.drop('SalePrice', axis=1)
y_train = train_set['SalePrice'].copy()



'''This here deals with the cateforical data. It replaces all the null values with none, since 
in the original data, a null value means that the instance did not have that given attribute, none is appropriate'''

# from sklearn.impute import SimpleImputer

# imputer = SimpleImputer(fill_value='none', strategy='constant')

# X = imputer.fit_transform(train_set)
# X = imputer.transform(train_set)
# train_tr = pd.DataFrame(X, columns=train_set.columns, index=train_set.index)
# train_tr

'This here deals with the cateforical data. It replaces all the null values with none, since \nin the original data, a null value means that the instance did not have that given attribute, none is appropriate'

In [12]:
'''Now that we have done the imputing above and it works, lets try to change it into a pipeline, so that we can apply it all at once'''
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

#here we have to distinguish between the numerical columns and the categorical columns, because the transformations being applied to each is different
num_attributes = list(X_train.select_dtypes(exclude=['object'])) #to select all num columns, we exclude any column with object types
cat_attributes = list(X_train.select_dtypes(include=['object'])) #here we select all columns with object types

# cat_pipeline = Pipeline([
#     ('one_hot', OneHotEncoder())
# ])

full_pipeline = ColumnTransformer([
    ('num', StandardScaler(), num_attributes),
    ('cat', OneHotEncoder(handle_unknown='ignore'), cat_attributes)
])

X_train_prepared = full_pipeline.fit_transform(X_train, y_train)

In [13]:
'''SELECT AND TRAIN YOUR MODEL'''
#first lets start with a linear regression model to see what kind of values we get
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()

lin_reg.fit(X_train_prepared, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
some_data = train_set.iloc[:5]
some_labels = y_train.iloc[:5]

some_data_prepared = full_pipeline.transform(some_data)
print('Predictions: ', lin_reg.predict(some_data_prepared))
print('Labels: ', list(some_labels))

Predictions:  [145152.07722357 170222.90594586  95470.25501555 165644.34459812
 170383.14343404]
Labels:  [145000, 178000, 85000, 175000, 127000]

note that the results above are quite off from the actual labels, so our model isnt great at predicting.
lets try to measure the root mean squared error to see how off we are

In [15]:
from sklearn.metrics import mean_squared_error

predictions = lin_reg.predict(X_train_prepared)
lin_mse = mean_squared_error(y_train, predictions)
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

18895.185448724387

In [16]:
y_train.describe()
#as you can see, the rmse is around 18,900, while the mean sale price is around 181,000

count      1168.000000
mean     181441.541952
std       77263.583862
min       34900.000000
25%      130000.000000
50%      165000.000000
75%      214925.000000
max      745000.000000
Name: SalePrice, dtype: float64

In [17]:
#lets see if we can get a better score, using a different model
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor()
tree_reg.fit(X_train_prepared, y_train)

#now that model is trained, lets evaluate it on the training set
predictions = tree_reg.predict(X_train_prepared)
tree_mse = mean_squared_error(y_train, predictions)
tree_rmse = np.sqrt(tree_mse)
print(tree_rmse)

0.0

note we get an rmse of 0. clearly this is not correct. the problem is that the model is overfitting. instead, 
lets use cross-validation to test our model and actually evaluate the performance of the tree regressor

In [18]:
#lets use cross_val_score to split our training set
from sklearn.model_selection import cross_val_score

'''cross_val_score(estimator, X, y, scoring= , cv= )'''
scores = cross_val_score(tree_reg, X_train_prepared, y_train, 
                        scoring='neg_mean_squared_error', cv=10)
#cv is the amount of different times the model will be evaluated
tree_rmse_scores = np.sqrt(-scores)

def display_scores(scores):
    '''This function displays the results in a neat way to look at'''
    print('Scores: ', scores)
    print('Mean: ', scores.mean())
    print('std: ', scores.std())

display_scores(tree_rmse_scores)

Scores:  [38699.14499033 60912.26903766 48832.55018205 44603.91406927
 51950.83786184 45702.31973456 37129.66254816 35715.04864205
 39063.20502525 34061.81760303]
Mean:  43667.07696942079
std:  8011.4222752611

In [19]:
#compute scores for Linear regression model to compare
lin_reg_scores = cross_val_score(lin_reg, X_train_prepared, y_train, 
                                scoring='neg_mean_squared_error', cv=10)
lin_rmse_scores = np.sqrt(-lin_reg_scores)

display_scores(lin_rmse_scores)

Scores:  [109585.75391255  32874.92719443  22491.97743204  46495.29003277
 104502.61086288  29490.62277859  50670.19058449  21309.52615828
  46717.17416725  26736.54627818]
Mean:  49087.461940144
std:  30612.259051640976

In [20]:
#now lets see how a random forest regressor works
from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor()

forest_reg.fit(X_train_prepared, y_train)
tree_predict = forest_reg.predict(X_train_prepared)
forest_mse = mean_squared_error(y_train, tree_predict)
forest_rmse = np.sqrt(forest_mse)
print('Forest RMSE: ', forest_rmse)
print('='*50)

forest_reg_scores = cross_val_score(forest_reg, X_train_prepared, y_train, 
                                   scoring='neg_mean_squared_error', cv=10)
forest_rmse_scores = np.sqrt(-forest_reg_scores)


display_scores(forest_rmse_scores)

C:\Users\sebas\Anaconda3\envs\ml_book\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

Forest RMSE:  13125.097336868683
==================================================
Scores:  [23025.71895278 36623.36395881 25777.06867833 40984.2395099
 43330.21226369 36498.49617751 28049.21977084 27795.30327948
 23877.74055969 26776.28732749]
Mean:  31273.76504785134
std:  7008.830612799235

This model is performing much better than our other two models looked at (the Mean from the cross_val_score is much lower) however, notice that the mean is still higher than the score on the training set (that is, the model is performing better on the training set than it is on the validation set). this means that the model is still overfitting

In [21]:
#first lets save these models so that we can come back to them later
# import joblib
# def save_models(model, save_name):
#     os.mkdir('saved_models')
#     save_path = os.path.join('saved_models', save_name + '.pkl')
#     joblib.dump(model, save_path)

In [22]:
'''Now lets try and fine tune the model'''

#NOTE THAT THIS BLOCK OF CODE WILL TAKE QUITE SOME TIME TO COMPUTE.

from sklearn.model_selection import GridSearchCV

parameters = [
    {'n_estimators': [1, 10, 100], 'max_features': [2, 4, 8, 16, 32]},
    {'bootstrap': [False], 'n_estimators': [10, 100], 'max_features': [8, 32]}
]

forest_reg = RandomForestRegressor()

grid_search = GridSearchCV(forest_reg, parameters, cv=5,
                          scoring = 'neg_mean_squared_error', 
                          return_train_score = True)

grid_search.fit(X_train_prepared, y_train)

C:\Users\sebas\Anaconda3\envs\ml_book\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=RandomForestRegressor(bootstrap=True, criterion='mse',
                                             max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators='warn', n_jobs=None,
                                             oob_score=False, random_state=None,
                                             verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid=[{'max_features': [2, 4, 8, 16, 32],
                          'n_estimators': [1, 10, 100]},
                         {'bootstrap': [False], 'max_features': [8, 32],
                          'n_estimators': [10, 100]}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring='neg_mean_squared_error', verbose=0)

In [23]:
grid_search.best_params_

{'bootstrap': False, 'max_features': 32, 'n_estimators': 100}

In [24]:
grid_search.best_estimator_

RandomForestRegressor(bootstrap=False, criterion='mse', max_depth=None,
                      max_features=32, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=100,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [25]:
cvres = grid_search.cv_results_
for mean_score, params in zip(cvres['mean_test_score'], cvres['params']):
    print(np.sqrt(-mean_score), params)

61659.3302194371 {'max_features': 2, 'n_estimators': 1}
41683.29162286365 {'max_features': 2, 'n_estimators': 10}
36370.375093748604 {'max_features': 2, 'n_estimators': 100}
56376.877910966425 {'max_features': 4, 'n_estimators': 1}
38809.821422648194 {'max_features': 4, 'n_estimators': 10}
34947.754808572776 {'max_features': 4, 'n_estimators': 100}
57514.788924233595 {'max_features': 8, 'n_estimators': 1}
36679.34215360826 {'max_features': 8, 'n_estimators': 10}
33416.27678565935 {'max_features': 8, 'n_estimators': 100}
55961.60449018221 {'max_features': 16, 'n_estimators': 1}
34381.70619097832 {'max_features': 16, 'n_estimators': 10}
31966.84629449845 {'max_features': 16, 'n_estimators': 100}
52989.99478230876 {'max_features': 32, 'n_estimators': 1}
33958.75305784288 {'max_features': 32, 'n_estimators': 10}
30788.37488084665 {'max_features': 32, 'n_estimators': 100}
33857.93777352183 {'bootstrap': False, 'max_features': 8, 'n_estimators': 10}
31976.36646062856 {'bootstrap': False, 'max_features': 8, 'n_estimators': 100}
33150.9444987411 {'bootstrap': False, 'max_features': 32, 'n_estimators': 10}
30247.399302078415 {'bootstrap': False, 'max_features': 32, 'n_estimators': 100}

You can also see the relative importance of each attribute for making accurate predictions

In [26]:
feature_importances = grid_search.best_estimator_.feature_importances_
print(feature_importances)

[4.04524449e-03 7.27732922e-03 1.90226089e-02 1.22445433e-01
 3.74387460e-03 4.46588815e-02 1.85738820e-02 1.00454468e-02
 3.05204498e-02 9.56228823e-04 6.74832853e-03 5.33446244e-02
 3.90347313e-02 2.80066489e-02 4.15532056e-04 1.04554566e-01
 3.03318026e-03 1.36832621e-04 2.61691275e-02 2.17983550e-03
 5.27765132e-03 1.46139627e-03 1.28111733e-02 1.35384460e-02
 2.58683786e-02 6.14459181e-02 4.54864249e-02 5.08149121e-03
 9.96700367e-03 9.87335376e-04 2.65101147e-04 2.90887531e-03
 2.19146682e-03 2.04836944e-04 2.99131066e-03 2.24407943e-03
 1.79647468e-05 3.08379035e-04 5.65404118e-05 9.38779258e-04
 1.34938479e-03 1.13194856e-05 3.50418423e-06 1.93840633e-04
 9.54338077e-05 2.16607132e-04 6.22412869e-04 5.88398744e-04
 4.08890134e-04 1.23807272e-03 1.52671923e-03 7.92079424e-04
 2.76432028e-04 1.29490071e-03 8.46183813e-07 1.08720701e-06
 7.04921809e-04 1.09776717e-03 1.47222055e-04 2.28774670e-05
 8.94532270e-04 1.00299792e-03 6.08765147e-04 2.31643785e-04
 9.30310236e-05 1.59759612e-06 4.30722235e-05 1.22214316e-04
 5.27869054e-04 5.05099994e-04 1.10138706e-03 1.87897230e-03
 2.11411219e-04 4.91578144e-05 7.72091799e-05 1.24071979e-04
 4.59716460e-04 9.44133650e-06 3.07589739e-04 2.82233893e-03
 9.73312071e-04 6.83770893e-04 9.93048231e-05 1.07213430e-04
 1.34712630e-04 5.07122132e-04 6.37455762e-04 1.87462517e-04
 4.76166050e-05 1.83384445e-04 3.76219341e-04 6.93460484e-04
 1.36885118e-04 1.95856012e-04 4.27360178e-05 7.55430100e-05
 6.45939674e-09 8.96366794e-06 3.87270187e-06 5.02216332e-06
 3.40148116e-04 9.65117048e-06 5.92007551e-06 4.00472003e-06
 1.11289126e-08 9.27138269e-07 1.08550081e-03 7.05866104e-05
 3.18970907e-04 1.25458032e-04 3.52668154e-04 4.17136500e-04
 2.60389978e-05 1.54374279e-03 8.81378502e-05 9.12523995e-05
 1.83391916e-03 5.73745229e-05 1.29760116e-04 1.84396496e-04
 1.59855468e-03 9.66611292e-05 3.65742360e-03 2.15976491e-05
 5.47666053e-06 7.56737430e-05 4.35447169e-04 8.03382715e-06
 2.63403010e-06 1.50285443e-04 4.73069104e-05 2.94748346e-04
 4.17119696e-05 2.59243246e-06 8.97462598e-05 1.24777972e-03
 1.46168416e-06 4.45207958e-04 7.32042107e-04 2.32518671e-06
 7.18017074e-04 2.35795015e-04 3.00175825e-05 4.27128472e-04
 6.53774226e-04 1.24167896e-03 9.37021873e-05 3.07123600e-05
 5.10127381e-06 7.55088054e-05 5.34853592e-04 6.42207578e-08
 4.22568408e-04 5.06969130e-04 3.13244505e-04 6.43307267e-04
 5.56269529e-06 4.67240229e-04 3.93554779e-06 4.60537215e-04
 7.98579732e-04 3.33095462e-04 3.47023657e-04 2.47550759e-05
 7.33388777e-05 6.66868513e-04 2.05844286e-03 1.09463736e-03
 9.07739784e-03 1.06087289e-04 8.05366080e-03 2.95762953e-02
 4.38682134e-05 1.94679111e-04 5.12024261e-04 4.56110676e-06
 6.78870678e-04 3.34335414e-04 9.72500533e-04 1.80329494e-02
 4.85220949e-05 3.64378195e-05 7.25329831e-06 1.15639126e-04
 3.70401412e-02 1.30962674e-04 8.94589887e-03 6.09722818e-03
 1.00495994e-04 2.05444094e-04 2.77690011e-04 1.97365461e-05
 5.09165500e-04 2.98004544e-04 7.92431056e-04 2.06311684e-03
 5.38051268e-04 1.43462271e-03 9.21772560e-05 5.54773255e-04
 2.26665919e-04 2.68830765e-03 1.62032398e-04 1.55468849e-04
 1.19764998e-03 1.85512332e-04 2.85264941e-04 8.70122781e-05
 1.07307058e-04 8.22355323e-05 1.75195111e-04 6.75980410e-04
 3.02345509e-06 2.69051093e-04 1.92710444e-04 2.40579402e-05
 2.39417403e-05 8.01558845e-07 1.38316278e-03 3.54969304e-04
 3.70676512e-04 1.88990585e-07 6.75384183e-04 2.60282796e-03
 2.06791131e-03 7.51936958e-06 1.30071844e-04 5.25946707e-05
 2.35500802e-06 1.92220114e-04 1.14914926e-02 9.19001457e-05
 3.36313355e-03 1.71450936e-02 8.45104002e-05 9.36263319e-05
 7.58651041e-05 1.35786505e-04 3.40600017e-04 1.97914716e-05
 7.74238394e-04 1.10699970e-02 8.42909179e-04 4.26671347e-05
 1.40610073e-03 1.09028729e-04 1.50864041e-03 4.33803573e-04
 4.49906369e-05 5.45255644e-03 1.91400181e-04 1.18797540e-03
 6.72823597e-05 2.41942069e-03 1.01337810e-03 1.21865120e-03
 1.08468910e-03 3.08062631e-03 4.98317751e-04 7.06397619e-04
 1.24338206e-04 1.27332763e-04 1.37455070e-06 1.33039945e-03
 7.18275463e-04 5.08082967e-07 6.75558581e-05 4.82685289e-05
 1.14711734e-05 8.24610745e-04 4.55368888e-04 1.14792145e-04
 3.64385324e-04 1.05440815e-03 2.75940070e-03 1.56091637e-05
 1.12435294e-04 1.27729108e-03 1.33049283e-04 2.59238199e-04
 1.75269201e-03 9.93913719e-06 9.81599069e-05 6.83889829e-06
 8.17990177e-06 1.04113783e-04 5.94996034e-06 8.57320510e-05
 8.64157144e-05 4.20966603e-05 1.54126204e-05 1.32237116e-05
 1.63816697e-05 1.17470409e-03 3.93776590e-06 1.14443112e-03
 1.87055709e-03 1.70154861e-05 2.99637002e-04 2.03337348e-04
 8.37086851e-04 1.49317796e-03]

In [39]:
attributes = num_attributes + cat_attributes
top_attributes = sorted(zip(feature_importances, attributes), reverse=True)[: 11]

print(top_attributes)

[(0.12244543335971901, 'OverallQual'), (0.10455456570599729, 'GrLivArea'), (0.06144591807771537, 'GarageCars'), (0.05334462438919003, 'TotalBsmtSF'), (0.04548642488394074, 'GarageArea'), (0.044658881523846665, 'YearBuilt'), (0.03903473128192103, '1stFlrSF'), (0.03052044981296888, 'BsmtFinSF1'), (0.028006648888767756, '2ndFlrSF'), (0.02616912749540104, 'FullBath'), (0.02586837859486125, 'GarageYrBlt')]

In [28]:
final_model = grid_search.best_estimator_

X_test = test_set.drop('SalePrice', axis=1)
X_test_prepared = full_pipeline.transform(X_test)

final_predictions = final_model.predict(X_test_prepared)

final_mse = mean_squared_error(y_test, final_predictions)
final_rmse = np.sqrt(final_mse)
print(final_rmse)

29937.14498822183

In [29]:
# '''From the list above, we see the list of most important attributes, from highest to lowest. based on this, we make a new list of the top attributes
# and get rid of the rest. now lets try to see how well our model does after simplifying it this way'''


# cats_to_keep = ['OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea', '1stFlrSF', 'YearBuilt', 'TotalBsmtSF', '2ndFlrSF', 'LotArea', 'BsmtFinSF1', 
#                'FullBath', 'TotRmsAbvGrd', 'GarageYrBlt']

# X_mod = train_set[cats_to_keep]

# X_mod
# #here i might need to make a custome pipeline that will select only those specific columns for further transformation

# scaler = StandardScaler()

# X_mod_tr = scaler.fit_transform(X_mod)

# scaler

In [30]:
test_data = load_data('test.csv')
index = test_data.Id

In [31]:
test_data_prepared = full_pipeline.transform(test_data)

predictions = final_model.predict(test_data_prepared)

predictions = pd.DataFrame(predictions)

final_predictions = predictions.set_index(index)
final_predictions.columns = ['SalePrice']

In [32]:
final_predictions.to_csv('iowa_predictions.csv')

In [33]:
final_predictions.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1459 entries, 1461 to 2919
Data columns (total 1 columns):
SalePrice    1459 non-null float64
dtypes: float64(1)
memory usage: 22.8 KB

In [34]:
final_predictions

      SalePrice
Id
1461  128447.00
1462  150014.98
1463  181765.62
1464  182862.90
1465  197940.56
...         ...
2915   99748.82
2916  103798.83
2917  175050.40
2918  123223.84
2919  233910.64

[1459 rows x 1 columns]